swagger: '2.0'
info:
  title: Business Central MCP Server v2
  description: Get Business Central data using MCP server. For instance customers, items, sales orders and create customers.
  version: '1.0'
host: mcp-bc-javi-chb7bue4evbkeyb0.westeurope-01.azurewebsites.net
basePath: /
schemes:
  - https
definitions:
  QueryResponse:
    type: object
    properties:
      jsonrpc:
        type: string
      id:
        type: string
      method:
        type: string
      params:
        type: object
      result:
        type: object
      error:
        type: object
paths:
  /mcp:
    post:
      summary: Business Central MCP Server
      parameters:
        - in: body
          name: body
          required: false
          schema:
            $ref: '#/definitions/QueryResponse'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Immediate Response
          schema:
            $ref: '#/definitions/QueryResponse'
        '201':
          description: Created and will follow callback
      operationId: BusinessCentralMCP
      tags:
        - Agentic
        - McpSse
securityDefinitions: {}
security: []
